---
title: "Trial-level analyses: univariate means"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true

---


# intro


```{r setup, include = FALSE}

## basics ----

library(here)
library(here)
library(tidyr)
library(dplyr)
library(magrittr)
library(data.table)
library(abind)
library(doParallel)
library(foreach)
library(mikeutils)
library(progress)
library(ggplot2)
library(grid)
library(gridExtra)
library(cowplot)
library(viridis)
library(purrr)

theme_set(theme_half_open())

source(here("code", "_constants.R"))
source(here("code", "_atlases.R"))
source(here("code", "_funs.R"))
source(here("code", "_read_behav.R"))


fnames <- c(
  "network_errts" = here("out", "icc", "means-trials_schaefer-network07_resid-errts.RDS"),
  "network_wherr" = here("out", "icc", "means-trials_schaefer-network07_resid-wherr.RDS"),
  "parcel_errts"  = here("out", "icc", "means-trials_schaefer-parcel_resid-errts.RDS"),
  "parcel_wherr"  = here("out", "icc", "means-trials_schaefer-parcel_resid-wherr.RDS")
)

cols <- c("subj", "task", "run", "trial.num", "trial.type", "acc")
trialinfo <- behav %>% map(~ select(.x, all_of(cols))) %>% rbindlist

## TODO:
##  - edit trialinfo so that displays

hi <- c("BX", "InCon", "RN")
lo <- c("BY", "Con", "NN")



## functions ----


get_trial_data <- function(name) {
  
  d <- readRDS(fnames[name])
  d <- rename(d, trial.num = trial)
  d <- merge(d, trialinfo, by = c("subj", "task", "run", "trial.num"))  ## bind just enough info
  ## TOD add error checking for expansion --- mismatched trials
  
}


get_ons <- function(d) {
  
  ## get 'ons' per task:
  
  d <- d[!is.na(value)]
  d_subj <- d[, .(value = mean(value)), by = c("subj", "task", "roi")]  ## aggregate

  rename(d_subj, on = value)
  
}


get_hilo <- function(d) {
  
  ## get hilo per task:
  
  d <- d[!is.na(value)]
  d$hilo <- as.character(NA)
  d[trial.type %in% hi]$hilo <- "hi"
  d[trial.type %in% lo]$hilo <- "lo"
  
  d_subj <- 
    d[hilo %in% c("hi", "lo"), .(value = mean(value)), by = c("subj", "task", "roi", "hilo")]  ## aggregate
  d_subj <- dcast(d_subj, subj + task + roi ~ hilo)  ## to wide
  d_subj[, hi_v_lo := hi - lo]  ## get contrast
  
  d_subj
  
}




```


# 'ONs'



```{r}


# ## network ----

d_subj_netw <- get_trial_data("network_errts") %>% get_ons

# d <- merge(d_subj_netw_errts, d_subj_netw_wherr, by = c("subj", "task", "roi"))


## plot:

d_subj_netw %>%
  
  ggplot(aes(roi, on)) +
  
  geom_hline(yintercept = 0) +
  stat_summary(aes(fill = task), fun = "mean", geom = "col", width = 0.5, position = position_dodge(width = 0.5)) +
  stat_summary(
    fun.data = "mean_cl_boot", geom = "errorbar", width = 0, size = 1.5, position = position_dodge(width = 0.5)
    ) +
  
  facet_grid(vars(task), scales = "free_y") +
  scale_fill_brewer(type = "qual", palette = 2) +
  theme(legend.position = 'none') +
  
  labs(y = "Mean ONs contrast (b)", x = "Network (Schaefer 7)")




## parcel ----

d_subj_parc <- get_trial_data("parcel_errts") %>% get_ons


## plot surfaces




```



# $hi-lo$


```{r}


## network ----

d_subj_netw <- get_trial_data("network_errts") %>% get_hilo

# d <- merge(d_subj_netw_errts, d_subj_netw_wherr, by = c("subj", "task", "roi"))


## plot:

d_subj_netw %>%
  
  ggplot(aes(roi, hi_v_lo)) +
  
  geom_hline(yintercept = 0) +
  stat_summary(aes(fill = task), fun = "mean", geom = "col", width = 0.5, position = position_dodge(width = 0.5)) +
  stat_summary(
    fun.data = "mean_cl_boot", geom = "errorbar", width = 0, size = 1.5, position = position_dodge(width = 0.5)
    ) +
  
  facet_grid(vars(task), scales = "free_y") +
  scale_fill_brewer(type = "qual", palette = 2) +
  theme(legend.position = 'none') +
  
  labs(y = "Mean hi vs lo contrast (b)", x = "Network (Schaefer 7)")




## parcel ----

d_subj_parc <- get_trial_data("parcel_errts") %>% get_hilo


## plot MD parcels:

d_subj_parc[roi %in% key_schaefer[schaefermd]$parcel] %>%
  
  ggplot(aes(task, hi_v_lo, fill = task)) +
  
  geom_hline(yintercept = 2) +
  stat_summary(fun = function(x) t.test(x)$statistic, geom = "col", width = 0.5, position = position_dodge(width = 0.5)) +

  facet_wrap(vars(roi)) +
  scale_fill_brewer(type = "qual", palette = 2) +
  theme(legend.position = 'none', axis.text.x = element_blank()) +
  
  labs(y = "Mean hi vs lo contrast (t-stat)", x = "Task (alphabetical)")


## plot surfaces


```





# GLM-free vs GLM-estimated


# wherr vs errts



## ...